name: Test with GlobalAppTesting

# Controls when the action will run.
on:
  pull_request:

jobs:
  test-with-gat:
    runs-on: ubuntu-latest
    steps:
      # required to get .gat.json file from your repository
      - uses: actions/checkout@v2
      - name: Test with GAT (android)
        uses: GlobalAppTesting/gat-actions-request-test@v2
        if: ${{ contains(github.event.pull_request.title, 'android') && !contains(github.event.pull_request.title, 'ios') }}
        with:
          api_key: ${{ secrets.GAT_API_KEY }}
          access_token: ${{ secrets.GAT_GH_ACCESS_TOKEN }}
          wait_for_finished_testing: false
          issue_prefix: android
      - name: Test with GAT (iOS)
        uses: GlobalAppTesting/gat-actions-request-test@v2
        if: ${{ contains(github.event.pull_request.title, 'ios') && !contains(github.event.pull_request.title, 'android') }}
        with:
          api_key: ${{ secrets.GAT_API_KEY }}
          access_token: ${{ secrets.GAT_GH_ACCESS_TOKEN }}
          wait_for_finished_testing: false
          issue_prefix: iOS
      - name: Test with GAT (API)
        uses: GlobalAppTesting/gat-actions-request-test@v2
        if: ${{ !contains(github.event.pull_request.title, 'ios') && !contains(github.event.pull_request.title, 'android') }}
        with:
          api_key: ${{ secrets.GAT_API_KEY }}
          access_token: ${{ secrets.GAT_GH_ACCESS_TOKEN }}
          wait_for_finished_testing: false
          issue_prefix: API
