name: GlobalAppTesting
on:
  schedule:
    - cron: '0 22 * * MON-FRI' # you have to quote this!
jobs:
  test-with-gat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with GAT
        uses: GlobalAppTesting/gat-actions-request-test@v1
        with:
          api_key: ${{ secrets.GAT_API_KEY }}
