name: GlobalAppTesting
on:
  release:
    types: [published]
jobs:
  test-with-gat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with GAT
        uses: GlobalAppTesting/gat-actions-request-test@v1.3
        with:
          api_key: ${{ secrets.GAT_API_KEY }}
          access_token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
